# django-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  secret_key: c2VjcmV0a2V5X3ZhbHVlCg==  # Base64 encoded secret

---
# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  password: cG9zdGdyZXNfcGFzc3dvcmQ=  # Base64 encoded password
